lingshi1={
    'picture':'零食1.jpg',
    'description':'休闲食品网红小吃坚果一整箱宿舍散装办公室',
    'name':'百草味-零食大礼包',
    'price':99.80,
    'goods_id':'lingshi1',
    'num':5000,
    'kind1':'shipin',
    'kind2':'零食',
    'admin':'test_user'
}
lingshi2={
    'picture':'零食2.jpg',
    'description':' 手撕风干牛肉干五香辣牛肉片500g1斤内蒙特产散装零食包邮',
    'name':'牛肉片',
    'price':19.98,
    'goods_id':'lingshi2',
    'num':2000,
    'kind1':'shipin',
    'kind2':'零食',
    'admin':'test_user'
}
lingshi3={
    'picture':'零食3.jpg',
    'description':' 杭州特产桂花绿豆饼糕点好吃的美食吃货抹茶零食',
    'name':'知味观绿豆糕',
    'price':29.90,
    'goods_id':'lingshi3',
    'num':1000,
    'kind1':'shipin',
    'kind2':'零食',
    'admin':'test_user'
}
chajiu1={
    'picture':'茶酒1.jpg',
    'description':'彼心旗舰店少女果味酒女士 组合装小瓶10%Vol抹茶275ml+蜜桃275ml',
    'name':'果味酒',
    'price':120.00,
    'goods_id':'chajiu1',
    'num':6000,
    'kind1':'shipin',
    'kind2':'茶酒',
    'admin':'test_user'
}
chajiu2={
    'picture':'茶酒2.jpg',
    'description':'万岁乐 加贺梅酒 720ml 青梅果酒',
    'name':'日本梅酒',
    'price':288.00,
    'goods_id':'chajiu2',
    'num':9000,
    'kind1':'shipin',
    'kind2':'茶酒',
    'admin':'test_user'
}
chajiu3={
    'picture':'茶酒3.jpg',
    'description':'桂花酒桂花酿陈年糯米酒甜酒高度米酒经典米酒买一送一',
    'name':'桂花米酒',
    'price':59.00,
    'goods_id':'chajiu3',
    'num':9580,
    'kind1':'shipin',
    'kind2':'茶酒',
    'admin':'test_user'
}
tiaoliaohongbei1={
    'picture':'调料烘焙1.jpg',
    'description':'味好美葱姜蒜粉28g/瓶 小瓶家用装调味料 烹饪香料 烘焙调料配料',
    'name':'味好美葱姜蒜粉',
    'price':7.80,
    'goods_id':'tiaoliaohongbei1',
    'num':5684,
    'kind1':'shipin',
    'kind2':'调料烘焙',
    'admin':'test_user'
}
tiaoliaohongbei2={
    'picture':'调料烘焙2.jpg',
    'description':'【5件包邮】欧芹碎20克 香芹片法香碎洋芫荽片披萨意面烘焙调味料',
    'name':'欧芹碎',
    'price':4.00,
    'goods_id':'tiaoliaohongbei2',
    'num':5544,
    'kind1':'shipin',
    'kind2':'调料烘焙',
    'admin':'test_user'
}
tiaoliaohongbei3={
    'picture':'调料烘焙3.jpg',
    'description':'包邮味品惠卡真调料510g香料调味粉 卡真粉西餐 烧烤腌制烘焙原料',
    'name':'卡真粉',
    'price':25.80,
    'goods_id':'tiaoliaohongbei3',
    'num':3942,
    'kind1':'shipin',
    'kind2':'调料烘焙',
    'admin':'test_user'
}
paocaishoushi1={
    'picture':'泡菜熟食1.jpg',
    'description':'蒋凤记五香肚片猪肚即食卤味熟食小吃私房凉菜下酒菜真空装130g*2风味香醇 下酒好菜 真空保鲜',
    'name':'五香肚片',
    'price':42.50,
    'goods_id':'paocaishoushi1',
    'num':8962,
    'kind1':'shipin',
    'kind2':'泡菜熟食',
    'admin':'test_user'
}
paocaishoushi2={
    'picture':'泡菜熟食2.jpg',
    'description':'小镇农家自制老坛四川泡菜泡萝卜真空袋装小吃榨菜风味重庆特产',
    'name':'四川泡菜',
    'price':7.80,
    'goods_id':'paocaishoushi2',
    'num':8992,
    'kind1':'shipin',
    'kind2':'泡菜熟食',
    'admin':'test_user'
}
paocaishoushi3={
    'picture':'泡菜熟食3.jpg',
    'description':'甜酸荞头新鲜腌制藠头下饭菜泡菜腌糖醋荞头水晶农家自制乔头叫头',
    'name':'甜酸荞头',
    'price':16.80,
    'goods_id':'paocaishoushi3',
    'num':8882,
    'kind1':'shipin',
    'kind2':'泡菜熟食',
    'admin':'test_user'
}
qunzhuang1={
    'picture':'裙装1.jpg',
    'description':'尘伊夏装新款加大码女装气质圆领七分袖拼接蕾丝钉珠连衣裙G17沁气质圆领七分袖拼接蕾丝钉珠连衣裙',
    'name':'钉珠连衣裙',
    'price':288,
    'goods_id':'qunzhuang1',
    'num':9882,
    'kind1':'nvzhuang',
    'kind2':'裙装',
    'admin':'test_user'
}
qunzhuang2={
    'picture':'裙装2.jpg',
    'description':'仙女裙超仙甜美小个子女装流行夏天裙子2019新款碎花雪纺连衣裙潮',
    'name':'雪纺连衣裙',
    'price':128,
    'goods_id':'qunzhuang2',
    'num':8982,
    'kind1':'nvzhuang',
    'kind2':'裙装',
    'admin':'test_user'
}
qunzhuang3={
    'picture':'裙装3.jpg',
    'description':'2019新款蕾丝连衣裙女夏装法式复古裙过膝夏天流行裙子显瘦仙女裙',
    'name':'仙女裙',
    'price':219,
    'goods_id':'qunzhuang3',
    'num':6882,
    'kind1':'nvzhuang',
    'kind2':'裙装',
    'admin':'test_user'
}
nvkuzhuang1={
    'picture':'女裤装1.jpg',
    'description':'米子旗2019年夏季新款女装萝卜哈伦裤女时尚百搭运动小脚裤九分裤',
    'name':'百搭运动小脚裤九分裤',
    'price':79.9,
    'goods_id':'nvkuzhuang1',
    'num':6982,
    'kind1':'nvzhuang',
    'kind2':'女裤装',
    'admin':'test_user'
}
nvkuzhuang2={
    'picture':'女裤装2.jpg',
    'description':'百褶阔腿裤女裤高腰垂感夏季新款宽松休闲裤雪纺长裤冰丝九分裤子',
    'name':'冰丝九分裤子',
    'price':39,
    'goods_id':'nvkuzhuang2',
    'num':6322,
    'kind1':'nvzhuang',
    'kind2':'女裤装',
    'admin':'test_user'
}
nvkuzhuang3={
    'picture':'女裤装3.jpg',
    'description':'妈妈夏装两件套新款阔太太洋气T恤小衫上衣中老年人女装时尚套装',
    'name':'中老年人女装时尚套装',
    'price':135,
    'goods_id':'nvkuzhuang3',
    'num':4822,
    'kind1':'nvzhuang',
    'kind2':'女裤装',
    'admin':'test_user'
}
nvkuzhuang3={
    'picture':'女裤装3.jpg',
    'description':'妈妈夏装两件套新款阔太太洋气T恤小衫上衣中老年人女装时尚套装',
    'name':'中老年人女装时尚套装',
    'price':135,
    'goods_id':'nvkuzhuang3',
    'num':4822,
    'kind1':'nvzhuang',
    'kind2':'女裤装',
    'admin':'test_user'
}
nvshangzhuang1={
    'picture':'女上装1.jpg',
    'description':'2019春夏新款洋气收腰大码修身七分袖小衫时尚女士碎花打底衫上衣',
    'name':'女士碎花打底衫',
    'price':138,
    'goods_id':'nvshangzhuang1',
    'num':4992,
    'kind1':'nvzhuang',
    'kind2':'女上装',
    'admin':'test_user'
}
nvshangzhuang2={
    'picture':'女上装2.jpg',
    'description':'2件69元】2019新款夏装宽松短袖t恤女装韩版女士白色纯棉上衣服潮',
    'name':'韩版女士白色纯棉上衣',
    'price':69.9,
    'goods_id':'nvshangzhuang2',
    'num':4992,
    'kind1':'nvzhuang',
    'kind2':'女上装',
    'admin':'test_user'
}
jiayongqingjie1={
    'picture':'家用清洁1.jpg',
    'description':'水垢发泡清洁剂浴室玻璃除垢剂瓷砖不锈钢清洗强力去污除霉清除剂泡沫去污 轻松瓦解污垢 买2送1 30天包退！',
    'name':'去污除霉清除剂',
    'price':68,
    'goods_id':'jiayongqingjie1',
    'num':4942,
    'kind1':'xihu',
    'kind2':'家用清洁',
    'admin':'test_user'
}
xiyuyongpin1={
    'picture':'洗浴用品1.jpg',
    'description':'沐浴露男士持久留香香体清爽古龙香水全身沫浴男专用洗发水浴套装持久留香清新淡雅 享受沐浴激情',
    'name':'去污除霉清除剂',
    'price':84,
    'goods_id':'xiyuyongpin1',
    'num':2482,
    'kind1':'xihu',
    'kind2':'洗浴用品',
    'admin':'test_user'
}
zhijin1={
    'picture':'纸巾1.jpg',
    'description':'30包抽纸实惠装本色纸巾家庭装整箱家用面巾纸餐巾纸纸抽卫生纸收藏加购 优先发货 30包整箱',
    'name':'家用面巾纸餐巾纸',
    'price':26.99,
    'goods_id':'zhijin1',
    'num':2238,
    'kind1':'xihu',
    'kind2':'纸巾',
    'admin':'test_user'
}
jiaju1={
    'picture':'家居1.jpg',
    'description':'筑梦师 原创金角鹿摆件 北欧风格家居装饰品玄关客厅电视柜酒柜',
    'name':'原创金角鹿摆件',
    'price':256,
    'goods_id':'jiaju1',
    'num':2998,
    'kind1':'baihuo',
    'kind2':'家居',
    'admin':'test_user'
}
jiafang1={
    'picture':'家纺1.jpg',
    'description':'lovo家纺全棉纯棉优雅田园风床上用品被套床单1.5/1.8米床柔软舒适 清新优雅 高雅清幽 清爽透气',
    'name':'床上用品被套床单',
    'price':399,
    'goods_id':'jiafang1',
    'num':2668,
    'kind1':'baihuo',
    'kind2':'家纺',
    'admin':'test_user'
}
riyongpin1={
    'picture':'日用品1.jpg',
    'description':'百货创意家居家生活用品日用品家用小东西厨房卫生间用品用具实用抽纸卷纸通用 半自动开关免打孔',
    'name':'卫生间用品',
    'price':38,
    'goods_id':'riyongpin1',
    'num':3288,
    'kind1':'baihuo',
    'kind2':'日用品',
    'admin':'test_user'
}
gerenyongpin1={
    'picture':'个人用品1.jpg',
    'description':'Mr.green德国指甲刀单个装家用中号指甲钳成人便携大号指甲剪原装德国工艺，进口不锈钢，出类拔萃的修甲体验',
    'name':'德国指甲刀',
    'price':47.8,
    'goods_id':'gerenyongpin1',
    'num':3918,
    'kind1':'baihuo',
    'kind2':'个人用品',
    'admin':'test_user'
}
shouji1={
    'picture':'手机1.jpg',
    'description':'【下单立减200元】Apple/苹果 iPhone Xs Max 256G 全网通4G手机 双卡双待苹果iphonexsmax原封国行 正品保障 苏宁快递',
    'name':'苹果手机',
    'price':9088,
    'goods_id':'shouji1',
    'num':2684,
    'kind1':'shuma',
    'kind2':'手机',
    'admin':'test_user'
}
wenju1={
    'picture':'文具1.jpg',
    'description':'得力中性笔0.5mm签字笔碳素笔12支学生用文具用品黑色水笔蓝黑笔办公签名笔水性笔红笔考试笔黑笔处方圆珠笔',
    'name':'中性笔',
    'price':19.2,
    'goods_id':'wenju1',
    'num':2514,
    'kind1':'shuma',
    'kind2':'文具',
    'admin':'test_user'
}
shoujipeijian1={
    'picture':'手机配件1.jpg',
    'description':'20000毫安迷你大容量充电宝自带线超薄便携小巧适用于苹果小米华为手机快充闪充无线专用移动电源女定制logo升级自带苹果安卓双线 量大可定制LOGO',
    'name':'充电宝',
    'price':118,
    'goods_id':'shoujipeijian1',
    'num':994,
    'kind1':'shuma',
    'kind2':'手机配件',
    'admin':'test_user'
}
diannaobijiben1={
    'picture':'电脑笔记本1.jpg',
    'description':'Dell/戴尔 成就3000 增强版8代4核i5 8G内存256GPcle固态盘超薄轻薄便携2年上门服务商务办公游戏笔记本电脑2年下一工作日上门服务 随机赠送包鼠套装！',
    'name':'笔记本电脑',
    'price':4298.9,
    'goods_id':'diannaobijiben1',
    'num':3685,
    'kind1':'shuma',
    'kind2':'电脑笔记本',
    'admin':'test_user'
}
shangwubangong1={
    'picture':'商务办公1.jpg',
    'description':'办公沙发简约现代小户型三人位接待西皮真皮商务办公室茶几组合商务格调，简约现代，舒适之选，睿智之选！',
    'name':'办公沙发',
    'price':458,
    'goods_id':'shangwubangong1',
    'num':252,
    'kind1':'shuma',
    'kind2':'商务办公',
    'admin':'test_user'
}
zhinengshebei1={
    'picture':'智能设备1.jpg',
    'description':'千幻魔镜10代vr眼镜手机专用rv虚拟现实3d游戏ar眼睛一体机苹果vivo华为oppo通用4D电影神器头戴式vr智能眼镜换一种视觉，看3d影院，在家体验电影院',
    'name':'vr眼镜',
    'price':668,
    'goods_id':'zhinengshebei1',
    'num':6685,
    'kind1':'shuma',
    'kind2':'智能设备',
    'admin':'test_user'
}
sheyingshexiang1={
    'picture':'摄影摄像1.jpg',
    'description':'BENRO百诺P1折叠手机拍摄稳定器三轴防抖手持vlog云台gopro全景陀螺仪自拍摄像摄影直播视频平衡器杆抖音神器折叠收纳 24小时长续航 可为手机无线充电',
    'name':'自拍杆',
    'price':689,
    'goods_id':'sheyingshexiang',
    'num':665,
    'kind1':'shuma',
    'kind2':'摄影摄像',
    'admin':'test_user'
}
nanxie1={
    'picture':'男鞋1.jpg',
    'description':'骆驼运动鞋男女 跑步鞋春夏季网面鞋子透气网鞋休闲女鞋超轻跑鞋中国马拉松联名款跑鞋 轻盈透气 耐磨缓震',
    'name':'骆驼运动鞋',
    'price':119,
    'goods_id':'nanxie1',
    'num':6225,
    'kind1':'xiexue',
    'kind2':'男鞋',
    'admin':'test_user'
} 
nvxie1={
    'picture':'女鞋1.jpg',
    'description':'回力女鞋高帮帆布鞋女学生韩版鞋子女2019潮鞋新款鞋子女夏季板鞋经典高帮 耐折度质检 10万次不开胶',
    'name':'女夏季板鞋',
    'price':69,
    'goods_id':'nvxie1',
    'num':625,
    'kind1':'xiexue',
    'kind2':'女鞋',
    'admin':'test_user'
}
yundongfuzhuang1={
    'picture':'运动服装1.jpg',
    'description':'迪卡侬运动套装男速干篮球健身短袖短裤训练跑步宽松运动服装RUNM专业面料 速干透气 柔软舒适',
    'name':'迪卡侬运动套装男',
    'price':89.8,
    'goods_id':'yundongfuzhuang1',
    'num':6222,
    'kind1':'yundong',
    'kind2':'运动服装',
    'admin':'test_user'
}
yundongjianshen1={
    'picture':'运动健身1.jpg',
    'description':'多德士仰卧起坐健身器材家用运动辅助器锻炼多功能健腹肌板仰卧板领券减20 领完即止 大扶手仰卧板送俯卧撑支',
    'name':'仰卧起坐健身器材',
    'price':168,
    'goods_id':'yundongjianshen1',
    'num':662,
    'kind1':'yundong',
    'kind2':'运动健身',
    'admin':'test_user'
}
huwai1={
    'picture':'户外1.jpg',
    'description':'北山狼睡袋成人户外旅行冬季加厚保暖大人便携式露营防寒单人隔脏夏季薄款1.0kg、1.1kg，2个拼接成双人睡袋',
    'name':'睡袋',
    'price':999,
    'goods_id':'huwai1',
    'num':6600,
    'kind1':'yundong',
    'kind2':'户外',
    'admin':'test_user'
}
caizhuang1={
    'picture':'彩妆1.jpg',
    'description':'玛丽黛佳腮红正品裸妆保湿自然提亮肤色修容高光腮红胭脂膏女彩妆一盒三色 刷出元气美肌 新手也适合',
    'name':'腮红胭脂膏',
    'price':55,
    'goods_id':'caizhuang1',
    'num':2641,
    'kind1':'meizhuang',
    'kind2':'彩妆',
    'admin':'test_user'
}
huli1={
    'picture':'护理1.jpg',
    'description':'海俪恩护理液隐形眼镜森呼吸500ml+120ml小瓶装近视美瞳水润正品效期新鲜 收藏加购享优先发货',
    'name':'隐形眼镜护理液',
    'price':19.8,
    'goods_id':'huli1',
    'num':2625,
    'kind1':'meizhuang',
    'kind2':'护理',
    'admin':'test_user'
}
qingjiemeirong1={
    'picture':'清洁美容1.jpg',
    'description':'璐瑶吸黑头神器电动吸出洗脸仪美容仪去毛孔机粉刺清洁面仪器脸部30天免费试用+无效可退+运费险+导出液3件套',
    'name':'吸黑头神器',
    'price':98,
    'goods_id':'qingjiemeirong1',
    'num':625,
    'kind1':'meizhuang',
    'kind2':'清洁美容',
    'admin':'test_user'
}
nanshangzhuang1={
    'picture':'男上装1.jpg',
    'description':'夏季薄款男士外套春秋款休闲夹克男上衣中年男装2019新款衣服宽松【可脱帽】秋季新款！大码夹克，品牌正品',
    'name':'秋款休闲夹克',
    'price':118,
    'goods_id':'nanshangzhuang1',
    'num':6555,
    'kind1':'nanzhuang',
    'kind2':'男上装',
    'admin':'test_user'
}
nankuzhuang1={
    'picture':'男裤装1.jpg',
    'description':'归心设计师男装男士香云纱休闲裤男桑蚕丝宽松小脚裤真丝薄款夏季',
    'name':'士香云纱休闲裤男',
    'price':1710,
    'goods_id':'nankuzhuang1',
    'num':2685,
    'kind1':'nanzhuang',
    'kind2':'男裤装',
    'admin':'test_user'
}
zhubaoshipin1={
    'picture':'珠宝饰品1.jpg',
    'description':'京润珍珠项链芳华近圆淡水珍珠项链送妈妈送婆婆女友礼物珠宝首饰经典小资款 圆润饱满 表皮光洁少瑕',
    'name':'淡水珍珠项链',
    'price':358,
    'goods_id':'zhubaoshipin1',
    'num':2625,
    'kind1':'zhuangshi',
    'kind2':'珠宝饰品',
    'admin':'test_user'
}
shoubiaojundao1={
    'picture':'手表军刀1.jpg',
    'description':'天王表男表正品防水休闲商务石英表日历情侣表间钨钢钢带男表品牌直营 分期免息',
    'name':'男表',
    'price':688,
    'goods_id':'shoubiaojundao1',
    'num':2225,
    'kind1':'zhuangshi',
    'kind2':'手表军刀',
    'admin':'test_user'
}
yanjing1={
    'picture':'眼镜1.jpg',
    'description':'普莱斯防蓝光辐射电脑近视眼镜框架女护眼睛超轻个性平光眼镜男潮一副很轻的防辐射防蓝光眼镜，可配近视镜',
    'name':'防辐射防蓝光眼镜',
    'price':179,
    'goods_id':'yanjing1',
    'num':995,
    'kind1':'zhuangshi',
    'kind2':'眼镜',
    'admin':'test_user'
}